version: '2'

services:

  redmine:
    build:
      context: docker/redmine-custom-uid/
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db
    volumes:
      - './data/redmine/:/usr/src/redmine/'
      - './data/files/:/usr/src/redmine/files/'

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
